export const CAPTURE_DURATION_MS = 1100
export const CHUTE_DURATION_MS = 800
export const ROLL_DURATION_MS = 600
export const WINNER_HOLD_MS = 300
export const SETTLE_DURATION_MS = 700
export const WINNER_EXIT_MS = CAPTURE_DURATION_MS + CHUTE_DURATION_MS + ROLL_DURATION_MS + WINNER_HOLD_MS
